title = "Somnath Rakshit"
description = "Somnath Rakshit's personal homepage"
baseURL = "https://somnath.pages.dev"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false  # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Somnath Rakshit"
  description = "Somnath Rakshit's personal website"
  favicon = "/favicon.ico"  # path to a .ico to use as favicon
  [params.footer]
    text = "Copyright Somnath Rakshit, 2021"
    url = "https://github.com/somnathrakshit"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/files/somnathrakshit_resume.pdf"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "Musings"
    url = "/musings"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 5
    ordered = false